import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components";
import SearchProvider from "@/providers/SearchProvider";
import { FavoritesProvider } from "@/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SearchProvider>
        <FavoritesProvider>
          <body className={inter.className}>
            <Navbar />
            {children}
          </body>
        </FavoritesProvider>
      </SearchProvider>
    </html>
  );
}
